[package]
name = "rooch_raffle"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/move-stdlib", rev = "main" }
MoveosStdlib = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/moveos-stdlib", rev = "main" }
RoochFramework = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/rooch-framework", rev = "main" }
BitcoinMove = { git = "https://github.com/rooch-network/rooch.git", subdir = "frameworks/bitcoin-move", rev = "main" }
app_admin = { git = "https://github.com/rooch-network/rooch.git", subdir = "apps/app_admin", rev = "main" }
gas_faucet = { git = "https://github.com/rooch-network/rooch.git", subdir = "apps/gas_faucet", rev = "main" }
twitter_binding = { git = "https://github.com/rooch-network/rooch.git", subdir = "apps/twitter_binding", rev = "main" }

[addresses]
rooch_raffle = "_"
app_admin = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
gas_faucet = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
twitter_binding = "0x701c21bf1c8cd5af8c42983890d8ca55e7a820171b8e744c13f2d9998bf76cc3"
std = "0x1"
moveos_std = "0x2"
rooch_framework = "0x3"
bitcoin_move =  "0x4"

[dev-addresses]
app_admin = "0x42"
gas_faucet = "0x43"
twitter_binding = "0x44"
